### ISSUE TITLE
where is checkpoint? pretrained weights to reproduce your results?

### ISSUE THREAD

**Issue by wonchul-kim** [gudovskiy/cflow-ad#1]
where is checkpoint? pretrained weights to reproduce your results?

**Comment by gudovskiy** [comment]
@wonchul-kim well, each MVTec/STC class has it own model with weights. So, for WRN-50 it would take 15GBs in total for MVTec to upload. Do you need some specific class/feature encoder?

**Comment by wonchul-kim** [comment]
@gudovskiy Thank you for your quick reply.
Hmm,, actually I wanted to test all class, but if you can't upload all weights, I would like to test some classes (Bottle, metal nut, Tile, Wood, pill). 

Thank you!

**Comment by gudovskiyd** [comment]
@wonchul-kim I uploaded pretrained MobileNetV3L weights and [added run instructions](https://github.com/gudovskiy/cflow-ad/#testing-pretrained-models)

**Comment by wonchul-kim** [comment]
@gudovskiy  Thank you so much!
