### ISSUE TITLE
Is it possible to get a class name of a surface/object on inference?

### ISSUE THREAD

**Issue by volkov-maxim** [gudovskiy/cflow-ad#10]
Hi, Denis!

Is it possible to get a class name of a surface/object on inference?
E.g.: fed to a model an image of a tile and after inference get a class name/class index of 'tile'.
If so, then how to do it?

**Comment by gudovskiy** [comment]
@volkov-maxim it is not possible with the current code, but you can take a look at https://github.com/izmailovpavel/flowgmm
