### ISSUE TITLE
Why num channels is divided here?

### ISSUE THREAD

**Issue by mysephi** [gudovskiy/cflow-ad#17]
According to your paper, what we should use is log(pz) in equation 8.
Why the log_prob is divided by the number of channels here?

https://github.com/gudovskiy/cflow-ad/blob/0d39848c988ad1c6b3c9b7f4bad40d52c1a75ceb/train.py#L77

**Comment by gudovskiy** [comment]
@mysephi usually, we would like to estimate likelihood per vector dimension as opposed to sum of likelihoods. this normalization is just a matter of convenience. In addition, most papers report bits/dim or nats/dim
