### ISSUE TITLE
Increase hyperparameter N

### ISSUE THREAD

**Issue by rvermeire** [gudovskiy/cflow-ad#19]
Hi,

When I increase hyperparameter N, for test_meta_epoch only, to 8192 I get an fps increase of 300% and SUM scores which are identical to N=256. I do not fully understand the code yet, so could you answer if this is wise to do?

**Comment by gudovskiy** [comment]
@rvermeire this increases batch size of the decoder (flow model). So, this indeed should improve speed at the expense of more GPU memory utilization.

**Comment by rvermeire** [comment]
Hi Denis,

Very clear, thanks!

**Comment by Howie86** [comment]
@gudovskiy 
Hi,
I am a bit confused about the impact of N, increase the value of N can improve the speed, will this affect the performance of the model? Do I need to keep the values of N in train and test the same?

If I set N to 512 during training and set it to a much larger value during testing to achieve higher inference speed, is this appropriate ?

Thanks a lot.

**Comment by gudovskiy** [comment]
@Howie86 yes, for inference you can set it to max value (even remove the loop at all)

**Comment by Howie86** [comment]
@gudovskiy Thanks for your reply, I understand.
