### ISSUE TITLE
why taking dataloader and training times very slow?

### ISSUE THREAD

**Issue by ingbeeedd** [gudovskiy/cflow-ad#2]
Hello, running the command below.

```bash
python3 main.py --gpu 0 --pro -inp 512 --dataset mvtec --class-name bottle
```

Can you tell me why it takes more time to train than the existing Anomaly algorithm and why it takes more time to bring dataloaders? Thank you for sharing code

**Comment by gudovskiy** [comment]
@ingbeeedd try to 
1. remove --pro estimation because it is slow CPU code
2. decrease -inp input resolution to 256/128

**Comment by gudovskiy** [comment]
3. use smaller feature extractor e.g. ResNet-18. For example:
python3 main.py --gpu 0 -enc resnet18 -inp 256 --dataset mvtec --class-name bottle
