### ISSUE TITLE
Large test loss, and thresholds

### ISSUE THREAD

**Issue by letmejoin** [gudovskiy/cflow-ad#4]
First, it's a great job, thanks for your sharing.
And, when I test bottle, train loss is very small, 10 epochs later, 0.06. But the test loss growth quickly, larger than 27000. At the 25th epoch, test loss is 6636421 while train loss 0.05. So, is this normal? I use default settings.

Then, a problem confused me a lot time. Without GTs, how can I chose thresholds of SEG? Both the auroc socres and F1 scores  require gt_mask, but the fact is no gt information for new data with only normal samples. Could you give some ideas? thks!

**Comment by gudovskiy** [comment]
@letmejoin 
1. You can think about loss as a negative log-likelihood. Then, an abnormal (only in test dataset) feature vectors have low log-likelihoods after successful training or, alternatively, high losses for such anomalous vectors. So, high test loss is exactly want we would like to achieve for abnormal feature vectors.

2. Threshold is a compromise between TPR and FPR (integrally measured by area under ROC). In case of absence of GT masks (TPR cannot be measured), there are two options:
    a) you have only normal test images. You cannot measure TPR, but still can measure FPR and set reasonable threshold with a certain margin.
    b) you have a collection of abnormal test images or artificially distorted normal test images. Then, you can either visually or quantitatively measure TPR and set threshold.

**Comment by letmejoin** [comment]
@gudovskiy The first question I have understood.
But the 2nd question, the two options you said is image-level(in my opinion). What I wanted to learn is how to get pixcel-level threshold. And the function of roc_auc_score doesn't accept normal sample only. I have normal and abnormal test images in image-level, but not in image-level. I can know which image is abnormal but not location of abnormal pixcels. So, if you have some advices? Thanks!

**Comment by letmejoin** [comment]
@gudovskiy And another question, have you test efficientnet-b5 performance compared with the other backbone?
In my testing with my own datasets, effcientnet-b5 is worst among wide-resnetx2, mobilenet-V3(small and large). Is efficientnet has low performance in your testing？The method of PaDiM uses the blocks 2, 4, 5 but you choose blocks 3, 5, 6. Why are you choose the three blocks?

**Comment by gudovskiy** [comment]
@letmejoin I didn't really experiment with EffNets a lot. I remember in my few tests it was slow. May be you are right about different pooling layer setup.

**Comment by gudovskiy** [comment]
@letmejoin you don't need to measure roc_auc_score for deployed model. But you can measure pixel-level FPR and set a threshold to avoid false alarms in option a). In b) some sort of surrogate TPR is needed to better tune threshold.
