### ISSUE TITLE
What is the B value here in extracting feature map

### ISSUE THREAD

**Issue by ThinhNguyenHoang** [gudovskiy/cflow-ad#40]
Hello, sir

Thanks for your wonderful repos and clearly explained paper.

But One point I have trouble understanding here is this line: 
https://github.com/gudovskiy/cflow-ad/blob/0d39848c988ad1c6b3c9b7f4bad40d52c1a75ceb/train.py#L55

What is the extracted B value, I assumed it was batch dimension when calling the feature extractor. But after inspecting the code, the ```train_meta_epoch``` already looping over the train_loader ```iterator``` --> We are only extracting feature maps from a single image at a time. 

Doesn't this mean that the B value here always equal 1 ?  If it is always 1, why do we take it into account in later computations (like E = B*S, fiber processing,...)

**Comment by gudovskiy** [comment]
@ThinhNguyenHoang B is the mini-batch size. Features are extracted with mini-batches, not a single image (unless specified so in config).

**Comment by ThinhNguyenHoang** [comment]
Thanks for your reply and great work.
