### ISSUE TITLE
Is it possible to get a class name of an anomaly on inference?

### ISSUE THREAD

**Issue by volkov-maxim** [gudovskiy/cflow-ad#9]
Hi, Denis!

Is it possible to get a class name of an anomaly on inference? 
E.g.: fed to model an image of a tile with crack and after inference get a class name/class index of anomaly.
If so, then how to do it?

**Comment by gudovskiy** [comment]
@volkov-maxim no, it is impossible with the current code. Your task is closer to supervised anomaly detection or, alternatively, you need to analyze density of anomaly data, which is not trivial
